name: Deploy flask to Heroku

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.9.13' # Replace '3.x' with the specific version you need

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run unittest for app
        run: python -m unittest discover -s Tests -p '*test_app.py'

      - name: Run unittest for game
        run: python -m unittest discover -s Tests -p '*test_game.py'

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
#    if: "contains(github.event.head_commit.message, '[deploy]')"

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.9.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "pyhang" # Replace with your Heroku app name
          heroku_email: "richardowingsjr@gmail.com" # Replace with your Heroku account email
